# Generated by Django 6.0.1 on 2026-01-31 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Numéro de table')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la table')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('prix_heure', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix par heure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('est_en_cours', models.BooleanField(default=True, verbose_name='En cours')),
                ('prix_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix total')),
                ('next_player', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prochain joueur')),
                ('est_paye', models.BooleanField(default=False, verbose_name='Est payé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.client', verbose_name='Client')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.table', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Partie',
                'verbose_name_plural': 'Parties',
                'ordering': ['-date_debut'],
            },
        ),
    ]
