# Generated by Django 6.0.1 on 2026-01-31 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_partie_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partie',
            name='prix_total',
        ),
        migrations.AddField(
            model_name='partie',
            name='prix',
            field=models.FloatField(default=0.0, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='partie',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='partie',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='manager.table', verbose_name='Table'),
        ),
    ]
