# Generated by Django 6.0.1 on 2026-01-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_remove_partie_prix_total_partie_prix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salle', models.CharField(default='Ma Salle de Billard', max_length=100)),
                ('tarif_base', models.FloatField(default=150.0)),
                ('tarif_reduit', models.FloatField(default=135.0)),
                ('seuil_prix', models.FloatField(default=1500.0)),
                ('devise', models.CharField(default='DT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres',
                'verbose_name_plural': 'Paramètres',
            },
        ),
    ]
